<?php namespace iAmirNet\Omnipay;

use App;
use Auth;
use Azarinweb\Minimall\Classes\Payments\DefaultPaymentGateway;
use Azarinweb\Minimall\Classes\Payments\PaymentGateway;
use Event;
use Backend;
use System\Classes\PluginBase;


class Plugin extends PluginBase
{
    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;

    public function pluginDetails()
    {
        return [
            'name'        => 'iamirnet.omnipay::lang.plugin.name',
            'description' => 'iamirnet.omnipay::lang.plugin.description',
            'author'      => 'iamirnet',
            'icon'        => 'icon-user',
            'homepage'    => 'https://iAmir.Net'
        ];
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $this->registerServices();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        //
    }

    public function registerPermissions()
    {
        return [];
    }

    public function registerSettings()
    {
        return [];
    }

    protected function registerServices()
    {

    }
}
